[package]
name = "ayed-nucore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ayed-config-parser = { path = "../ayed-config-parser" }

regex = "1.9.5"
